config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


resources :guests, only: [:show, :index, :new, :create, :destroy] do
  resources :amounts, only: [:create] #we don't need the destroy here, because if we wanna destroy a dose we don't need this here

end

resources :amounts, only: [:destroy]

root 'guests#index'

end

app/models/amount.rb
class Amount < ApplicationRecord
  belongs_to :present
  belongs_to :guest


  #An Amount must have a description, a guest and a present, and [guest, present] pairings should be unique.
  validates :desc, presence: true
  validates :present_id, uniqueness: { scope: :guest}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/guest.rb
class Guest < ApplicationRecord
  has_many :amounts
  has_many :presents, through: :amounts
  validates :name, presence: true

end

app/models/present.rb
class Present < ApplicationRecord
  has_many :amounts
  has_many :guests, through: :amounts
  validates :name, presence: true

end

app/controllers/amounts_controller.rb
class AmountsController < ApplicationController



  def create

    @guest = Guest.find(params[:guest_id])
    @amount = Amount.new(params_dose)
    @amount.guest = @guest
    if @amount.save
      redirect_to @guest
    else
      render "guests/show"
    end
  end

  def destroy
    @amount = Amount.find(params[:id])
    @amount.destroy
    redirect_to guest_path(@amount.guest)
  end


  def params_dose
    params.require(:amount).permit(:desc, :present_id)
  end



end


# <% @amount.presents_id.each do |present| %>
# <p><%= present.name%></p>
# <% end %>

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController


  def index
    @guests = Guest.all
  end

  def show
    @guest = Guest.find(params[:id])
    @amount = Amount.new
  end

  def new
    @guest = Guest.new
  end

  def create
      @guest = Guest.new(guest_params)
      if @guest.save
        redirect_to guest_path(@guest)
      else
        render new_guest_path(@guest)
      end
  end


  def destroy
     @guest = Guest.find(params[:id])
     @guest.destroy
     redirect_to guests_path
  end


private

  def guest_params
      params.require(:guest).permit(:name)
  end



end

app/controllers/presents_controller.rb
class PresentsController < ApplicationController


end

app/helpers/amounts_helper.rb
module AmountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/presents_helper.rb
module PresentsHelper
end

app/views/guests/index.html.erb
<div class="container">
<h1>Presents for Marianne and Linus</h1>

<%= link_to 'add a new guest', new_guest_path, class:"btn btn-success" %>
</br>

<%= cl_image_tag("rfvnniolmmnpbrbk3hhj",
      width: 400, height: 300, crop: :fill) %>

<div class="listitemstobi">
<div class="list-group">
<% @guests.each do |guest| %>
<%= link_to guest_path(guest) do %>
<div class="list-group-item">
  <%= guest.name %>
  </div>
<% end %>
<% end %>
</div>
</div>
</div>


</div>

app/views/guests/new.html.erb
<h1>create a new guest</h1>

<%= simple_form_for @guest do |f| %>
Name: <%= f.text_field :name, placeholder: 'type name' %>
<%= f.submit %>
<% end %>

app/views/guests/show.html.erb
<div class="container">
<h1><%= @guest.name %></h1>

<%= link_to 'back', guests_path, class:"btn btn-danger"%>
<%= link_to 'remove this guest', guest_path(@guest), method: :delete %>

<p>This guest's name ;)  <%= @guest.name%> </p>



<%= simple_form_for [@guest, @amount] do |f| %>
<h4>Amounts:</h4>
<%= f.input :desc, placeholder: 'how much' %>
<%= f.input :present_id, collection: Present.order(name: :asc).all %>
<%= f.submit "CREATE", class:"btn btn-primary"%>
<% end %>
<ul>
  <% @guest.amounts.each do |amount| %>
<li><%= amount.desc %> of <%= amount.present.name %> (<%= link_to 'remooove', amount_path(amount), method: :delete %>) </li>
  <% end %>
</ul>

<div class="list-group">
<% @guest.amounts.each do |amount| %>

<div class="list-group-item">
<p><%= Present.find(amount.present_id).name%></p>
<p><%= amount.desc%></p>
</div>

<% end %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>